allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  cpu-features: true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  ssh2: true
  unrs-resolver: true
  vue-demi: true
ignoredBuiltDependencies:
  - "@parcel/watcher"
  - '@prisma/engines'
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
onlyBuiltDependencies:
  - '@prisma/client'
  - prisma
