export const modules = [
  {
    id: 1,
    parent_id: null,
    key: "dashboard",
    title: "Dashboard",
    route_name: "dashboard",
    href: "/dashboard",
    icon: "LayoutDashboard",
    section: "General",
    ordering: 1,
    active: "S",
    description: "Panel principal del sistema",
    permissions_required: null,
    created_at: "2026-02-25 02:06:11.0",
    updated_at: "2026-02-25 02:06:11.0"
  },
  {
    id: 2,
    parent_id: null,
    key: "solicitudes",
    title: "Solicitudes",
    route_name: "solicitudes.index",
    href: "/solicitudes",
    icon: "FileText",
    section: "Créditos",
    ordering: 2,
    active: "S",
    description: "Gestión de solicitudes de crédito",
    permissions_required: ["solicitudes.read"],
    created_at: "2026-02-25 02:06:11.0",
    updated_at: "2026-02-25 02:06:11.0"
  },
  {
    id: 3,
    parent_id: 2,
    key: "solicitudes.create",
    title: "Nueva Solicitud",
    route_name: "solicitudes.create",
    href: "/solicitudes/create",
    icon: "Plus",
    section: "Créditos",
    ordering: 1,
    active: "S",
    description: "Crear nueva solicitud de crédito",
    permissions_required: ["solicitudes.create"],
    created_at: "2026-02-25 02:06:11.0",
    updated_at: "2026-02-25 02:06:11.0"
  },
  {
    id: 4,
    parent_id: null,
    key: "trabajadores",
    title: "Trabajadores",
    route_name: "trabajadores.index",
    href: "/trabajadores",
    icon: "Users",
    section: "Recursos",
    ordering: 3,
    active: "S",
    description: "Gestión de trabajadores",
    permissions_required: ["trabajadores.read"],
    created_at: "2026-02-25 02:06:11.0",
    updated_at: "2026-02-25 02:06:11.0"
  },
  {
    id: 5,
    parent_id: null,
    key: "empresas",
    title: "Empresas",
    route_name: "empresas.index",
    href: "/empresas",
    icon: "Building2",
    section: "Recursos",
    ordering: 4,
    active: "S",
    description: "Gestión de empresas convenio",
    permissions_required: ["empresas.read"],
    created_at: "2026-02-25 02:06:11.0",
    updated_at: "2026-02-25 02:06:11.0"
  },
  {
    id: 6,
    parent_id: null,
    key: "users",
    title: "Usuarios",
    route_name: "users.index",
    href: "/users",
    icon: "UserCog",
    section: "Administración",
    ordering: 5,
    active: "S",
    description: "Gestión de usuarios del sistema",
    permissions_required: ["users.read"],
    created_at: "2026-02-25 02:06:11.0",
    updated_at: "2026-02-25 02:06:11.0"
  },
  {
    id: 7,
    parent_id: null,
    key: "reports",
    title: "Reportes",
    route_name: "reports.index",
    href: "/admin/reportes",
    icon: "BarChart3",
    section: "Reportes",
    ordering: 6,
    active: "S",
    description: "Reportes y estadísticas",
    permissions_required: ["reports.read"],
    created_at: "2026-02-25 02:06:11.0",
    updated_at: "2026-02-25 02:06:11.0"
  },
  {
    id: 8,
    parent_id: null,
    key: "settings",
    title: "Configuración",
    route_name: "settings.index",
    href: "/settings",
    icon: "Settings",
    section: "Administración",
    ordering: 7,
    active: "S",
    description: "Configuración del sistema",
    permissions_required: ["system.admin"],
    created_at: "2026-02-25 02:06:11.0",
    updated_at: "2026-02-25 02:06:11.0"
  }
];
