export const roles = [
  {
    id: 1,
    nombre: "administrator",
    descripcion: "Administrador del sistema con acceso completo",
    permisos: [
      "users.create",
      "users.read",
      "users.update",
      "users.delete",
      "solicitudes.create",
      "solicitudes.read",
      "solicitudes.update",
      "solicitudes.delete",
      "trabajadores.read",
      "empresas.read",
      "reports.read",
      "system.admin",
    ],
    color: "#DC2626",
    orden: 1,
    activo: true,
    created_at: "2026-02-25 02:06:11.0",
    updated_at: "2026-02-25 02:06:11.0",
  },
  {
    id: 2,
    nombre: "adviser",
    descripcion: "Asesor de crédito con acceso a solicitudes",
    permisos: [
      "solicitudes.create",
      "solicitudes.read",
      "solicitudes.update",
      "trabajadores.read",
      "empresas.read",
      "reports.read",
    ],
    color: "#2563EB",
    orden: 2,
    activo: true,
    created_at: "2026-02-25 02:06:11.0",
    updated_at: "2026-02-25 02:06:11.0",
  },
  {
    id: 3,
    nombre: "user_empresa",
    descripcion: "Usuario de empresa que postula créditos",
    permisos: [
      "solicitudes.create",
      "solicitudes.read",
      "solicitudes.update",
      "empresas.read",
    ],
    color: "#059669",
    orden: 3,
    activo: true,
    created_at: "2026-02-25 02:06:11.0",
    updated_at: "2026-02-25 02:06:11.0",
  },
  {
    id: 4,
    nombre: "user_trabajador",
    descripcion: "Usuario trabajador que postula créditos",
    permisos: ["solicitudes.create", "solicitudes.read", "solicitudes.update"],
    color: "#7C3AED",
    orden: 4,
    activo: true,
    created_at: "2026-02-25 02:06:11.0",
    updated_at: "2026-02-25 02:06:11.0",
  },
];
